import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar />
      <Head>
        <title>OxynWare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Oxynware</h1>

        <p className={styles.description}>Software Systems </p>

        <div className={styles.grid}>
          <a
            href="https://matthew-howe.github.io/knightstour/"
            className={styles.card}
          >
            <h2>OxynTrader&rarr;</h2>
            <p>Real-Time data and tooling for markets and securities.</p>
          </a>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>OxynPoker&rarr;</h2>
            <p>Nash Equilibrium solution terminal and training game.</p>
          </a>
        </div>
      </main>
      <Footer />

    </div>
  );
}
